# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad7cb03ff1b9709548bc18bfe60376d724b29b4a06dc9c756d2771cf2d4a47644a26b651c0a353427ddfe86913054ed673579d1e31ec47d825a477bcd5d2fe6

test:
  secret_key_base: 6e7247558bf973dbb668a048c82481a9237766c046b4df35195c67bd4c0a54b5244443324569b975b553d345f17e380d41e8140b17e9665965fafaf9be2c0791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
